"""init schema

Revision ID: a54744dcf7d3
Revises: 
Create Date: 2025-12-11 18:07:37.693356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54744dcf7d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.create_table('alembic_version',
                    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
                    )
    op.create_table('failed_logins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('logid', sa.Integer(), nullable=False),
    sa.Column('usertype', sa.String(length=50), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('actiontime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('logid')
    )
    op.create_table('students',
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('registrationdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('studentid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('teachers',
    sa.Column('teacherid', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('teacherid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='student', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('teacherid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacherid'], ['teachers.teacherid'], ),
    sa.PrimaryKeyConstraint('courseid')
    )
    op.create_table('sessions',
    sa.Column('token', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('assignments',
    sa.Column('assignmentid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('Домашнее задание', 'Контрольная работа', 'Тест', name='assignment_type'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['courses.courseid'], ),
    sa.PrimaryKeyConstraint('assignmentid')
    )
    op.create_table('groups',
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('creationdate', sa.Date(), nullable=False),
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['courses.courseid'], ),
    sa.PrimaryKeyConstraint('groupid')
    )
    op.create_table('results',
    sa.Column('resultid', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('submissiondate', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('assignmentid', sa.Integer(), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignmentid'], ['assignments.assignmentid'], ),
    sa.ForeignKeyConstraint(['studentid'], ['students.studentid'], ),
    sa.PrimaryKeyConstraint('resultid')
    )
    op.create_table('schedule',
    sa.Column('scheduleid', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.Column('teacherid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['courses.courseid'], ),
    sa.ForeignKeyConstraint(['groupid'], ['groups.groupid'], ),
    sa.ForeignKeyConstraint(['teacherid'], ['teachers.teacherid'], ),
    sa.PrimaryKeyConstraint('scheduleid')
    )
    op.create_table('student_group',
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('joindate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['groupid'], ['groups.groupid'], ),
    sa.ForeignKeyConstraint(['studentid'], ['students.studentid'], ),
    sa.PrimaryKeyConstraint('studentid', 'groupid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('student_group')
    op.drop_table('schedule')
    op.drop_table('results')
    op.drop_table('groups')
    op.drop_table('assignments')
    op.drop_table('user_profiles')
    op.drop_table('sessions')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('logs')
    op.drop_table('failed_logins')
    # ### end Alembic commands ###
